// 模拟数据 - 用于API接口调试和降级
import type { Banner, Booth, Product } from '@/types/api';

export const mockBanners: Banner[] = [
  {
    id: 1,
    title: '找货就上代拿网',
    imageUrl: 'https://picsum.photos/350/160?random=1',
    linkUrl: '/cooperation',
    linkType: 'external',
    sortOrder: 1,
  },
  {
    id: 2,
    title: '代拿费低至1元',
    imageUrl: 'https://picsum.photos/350/160?random=2',
    linkUrl: '/dropship',
    linkType: 'external',
    sortOrder: 2,
  },
];

export const mockBooths: Booth[] = [
  {
    id: '1',
    boothName: '舒克',
    description: '专业手机数码批发',
    imageUrl: 'https://picsum.photos/60/60?random=3',
    score: 95.5,
    market: '工业',
    address: 'A2005',
    rank: 1,
    isHot: true,
  },
  {
    id: '2',
    boothName: '星辉通讯',
    description: '优质电子产品供应商',
    imageUrl: 'https://picsum.photos/60/60?random=4',
    score: 92.3,
    market: '康乐',
    address: '5A60-61',
    rank: 2,
    isHot: true,
  },
  {
    id: '3',
    boothName: '永承',
    description: '专业配件批发',
    imageUrl: 'https://picsum.photos/60/60?random=5',
    score: 90.1,
    market: '工业',
    address: 'B1203',
    rank: 3,
  },
  {
    id: '4',
    boothName: '鑫源科技',
    imageUrl: 'https://picsum.photos/60/60?random=6',
    score: 88.9,
    market: '华强北',
    address: 'B1001',
  },
  {
    id: '5',
    boothName: '天诚电子',
    imageUrl: 'https://picsum.photos/60/60?random=7',
    score: 87.2,
    market: '赛格',
    address: 'C301',
  },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    name: '苹果14寸MacBook Pro',
    description: 'M4Pro芯片，原装正品',
    price: 11600,
    imageUrl: 'https://picsum.photos/200/200?random=8',
    boothId: '1',
    boothName: '舒克',
    score: 4.8,
    sales: 18,
    isHot: true,
  },
  {
    id: 2,
    name: 'ROG华硕RTX5070Ti',
    description: '猛禽天选白',
    price: 5099,
    imageUrl: 'https://picsum.photos/200/200?random=9',
    boothId: '2',
    boothName: '星辉通讯',
    score: 4.6,
    sales: 7,
  },
  {
    id: 3,
    name: 'iPhone 15 Pro Max',
    description: '256GB 深空黑色',
    price: 8999,
    imageUrl: 'https://picsum.photos/200/200?random=10',
    boothId: '1',
    boothName: '舒克',
    score: 4.9,
    sales: 45,
    isHot: true,
  },
  {
    id: 4,
    name: 'iPad Pro 12.9英寸',
    description: 'M2芯片 512GB',
    price: 7299,
    imageUrl: 'https://picsum.photos/200/200?random=11',
    boothId: '3',
    boothName: '永承',
    score: 4.7,
    sales: 23,
  },
  {
    id: 5,
    name: 'AirPods Pro 2',
    description: '主动降噪 USB-C',
    price: 1899,
    imageUrl: 'https://picsum.photos/200/200?random=12',
    boothId: '2',
    boothName: '星辉通讯',
    score: 4.8,
    sales: 67,
  },
  {
    id: 6,
    name: 'MacBook Air M3',
    description: '13英寸 256GB 午夜色',
    price: 8599,
    imageUrl: 'https://picsum.photos/200/200?random=13',
    boothId: '4',
    boothName: '鑫源科技',
    score: 4.6,
    sales: 12,
  },
];